"""Shared DTO helpers used by both FastAPI routers and MCP servers."""
from __future__ import annotations

from typing import Any


def build_transcribe_params(
    *,
    language: str,
    model_size: str,
    min_speakers: int,
    max_speakers: int,
    vad_threshold: float,
    noise_reduce: bool,
    reduction_db: int,
    voice_enhance: bool,
    apply_gain: bool,
    target_lufs: float,
    remove_silence: bool,
    silence_thresh: int,
    min_silence_len: int,
    beam_size: int,
    best_of: int,
    whisper_temp: float,
    temperature_increment_on_fallback: float,
    compression_ratio_threshold: float,
    logprob_threshold: float,
    no_speech_threshold: float,
    condition_on_previous_text: bool,
    initial_prompt: str | None,
    length_penalty: float,
    patience: float | None,
    suppress_blank: bool,
    suppress_tokens: str,
    word_timestamps: bool,
    keep_cache: bool,
    progress_callback: Any = None,
) -> dict[str, Any]:
    """Build a unified transcribe parameter dict shared across routers and MCP servers."""
    return {
        "language": language,
        "model_size": model_size,
        "min_speakers": min_speakers,
        "max_speakers": max_speakers,
        "vad_threshold": vad_threshold,
        "noise_reduce": noise_reduce,
        "reduction_db": reduction_db,
        "voice_enhance": voice_enhance,
        "apply_gain": apply_gain,
        "target_lufs": target_lufs,
        "remove_silence": remove_silence,
        "silence_thresh": silence_thresh,
        "min_silence_len": min_silence_len,
        "beam_size": beam_size,
        "best_of": best_of,
        "whisper_temp": whisper_temp,
        "temperature_increment_on_fallback": temperature_increment_on_fallback,
        "compression_ratio_threshold": compression_ratio_threshold,
        "logprob_threshold": logprob_threshold,
        "no_speech_threshold": no_speech_threshold,
        "condition_on_previous_text": condition_on_previous_text,
        "initial_prompt": initial_prompt,
        "length_penalty": length_penalty,
        "patience": patience,
        "suppress_blank": suppress_blank,
        "suppress_tokens": suppress_tokens,
        "word_timestamps": word_timestamps,
        "keep_cache": keep_cache,
        "progress_callback": progress_callback,
    }
